[package]
name = "rpg"
version = "0.1.0"
authors = ["travistrue2008 <travis.true08@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.100", features = ["derive"] }
serde_json = "1.0"
